### ISSUE TITLE
[to-do] Raids

### ISSUE THREAD

**Issue by EPuncker** [PrinterLUA/FORGOTTENSERVER-ORTS#1055]
Assigned to @EPuncker
I'll re-do/update most of them, just made this to keep track of the issue

http://tibia.wikia.com/wiki/Raids
Currently missing:

- [ ] The Evil Eye
- [ ] POI Bosses
- [ ] Djinn Raids near Ankrahmun
- [ ] Vampire Raid in Shadow Tomb
- [ ] Vampire Raid in Tarpit Tomb
- [ ] Troll Raid North-West of Carlin
- [ ] Wasp Raid North of Carlin
- [ ] Undead Raid on Ghostlands
- [ ] Orc Raid on Carlin (Gives amazon shield)
- [ ] Orc Raid on Femor Hills (Gives amazon armor and helmet)
- [ ] Hunter and Wild Warrior Raid on Femor Hills
- [ ] Amazon Raid North of Carlin
- [ ] Wasps in Darashia

more to come
