### ISSUE TITLE
[to-do] Missing NPC spawns

### ISSUE THREAD

**Issue by ghost** [PrinterLUA/FORGOTTENSERVER-ORTS#1170]
I've made this to track NPCs that are not present in map, feel free to add them and refer to this issue in order to update the list!

_Work In Progress_
- [x] Benevola
- [x] An Ancient Priest
- [x] Cruleo
- [x] A Dark Priestess
- [x] Edron Guardsman
- [x] Eliza
- [x] Jack
- [x] Sister Of Jack
- [x] Mother Of Jack
