### ISSUE TITLE
Houses Issues

### ISSUE THREAD

**Issue by tarantonio** [PrinterLUA/FORGOTTENSERVER-ORTS#323]
_Edited: Removed fixed things_
- [x] ~~You see an open door.ItemID: [5518].Position: [X: 33335] [Y: 32762] [Z: 6].Missing house: http://tibia.wikia.com/wiki/Low_Waters_Observatory~~
- ~~You see a trapdoor.ItemID: [8285].Position: [X: 33340] [Y: 32755] [Z: 6]. Stair bugged~~
- ~~Position: [X: 32379] [Y: 32759] [Z: 7] Stairs missing here~~
- [x] ~~You see an open door.ItemID: [10472].Position: [X: 32262] [Y: 32237] [Z: 7]. Missing house:http://tibia.wikia.com/wiki/Open-Air_Theatre~~
- [x] ~~House and island missing : http://tibia.wikia.com/wiki/Eastern_House_of_Tranquility~~
- [ ] House missing: http://tibia.wikia.com/wiki/Caveman_Shelter
- [x] ~~House missing: http://tibia.wikia.com/wiki/The_Lair~~
- [ ] Lost Cavern house missing #303
- [ ] Hare's Den map bug #289 
- [ ] Old Sanctuary of God King Qjell map bug #302
