### ISSUE TITLE
NPC issues

### ISSUE THREAD

**Issue by tarantonio** [PrinterLUA/FORGOTTENSERVER-ORTS#473]
- [x] Humphrey doesnt give correct blessing (se coments below)
- [x] ~~Nielson: http://tibia.wikia.com/wiki/Nielson don't have travel script~~
- [x] ~~Malunga: http://tibia.wikia.com/wiki/Malunga don't buy/sell like RL~~
- [x] ~~Bonifacius: you can't buy eggs~~
- [x] ~~Missing NPC: Position: [X: 32670] [Y: 31657] [Z: 6] http://tibia.wikia.com/wiki/Shiriel~~
- [x] ~~Problem with npc Habdel/Ishina. He/She doesn't has got a script for addon. #477~~ Extra Issue for Outfit quest
- [x] ~~Ajax don't work that like should. #476~~
- [x] ~~Bron don't work that like should. #476~~
- [x] ~~NPC Trisha doesnt work. #465~~
- [x] NPC Raymond Striker not work #427
- [x] ~~Problem with npc Norma #414~~ 
- [x] ~~NPC Glomelvis The soul melody task doesn't work. #369~~ moved to Bigfoot Burden Issues
- [x] ~~Missing Npc Sandomo no give the quests #353~~   Extra Issue for Roshamuhl quest
- [x] Captain Haba is not working #243  
- [x] ~~Djinns trade(SOVED) #235~~
- [x] npc Lurgi #64 
- [x] ~~Brodrosch doesnt sell Ore Wagon tickets.~~
- [x] ~~Zumtah.lua error in callback~~
- [x] ~~Chondur.lua error compare nil value~~
- [x] ~~Wizard Addon of the Banshee Queen #506~~
- [x] Lyres don't work in the near of Edala to get a Diapason #346 
- [x] NPC Yasir has no (Please check if he buys items) #309 
- [x] ~~NPC Pompan is not buying all items (Tomes Quest missing) #309~~
- [x] After completing a task with Grizzly Adams, you get the point of task nor point to kill the boss. #309 
- [x] ~~edron jack fate don't transport to thais in real tibia it transport #540~~
- [x] ~~Nelliem: http://tibia.wikia.com/wiki/Nelliem don't sell like RL #658~~
- [x] ~~Npc lazaram is missing quest for addon warmaster? #678~~
- [x] ~~NPC Shauna does nothing #729~~
