### ISSUE TITLE
Bigfoot Burden Quest Issues

### ISSUE THREAD

**Issue by Royalot** [PrinterLUA/FORGOTTENSERVER-ORTS#484]
**I merge here all Bigfoot Burden Quest Issues**
- [ ] bigfootBurdenQuestMusic.lua not works fine #434
- [ ] error on Gnomerik #448 
- [ ] Not have teleport War Zone I II III #248 
- [ ] ActionIDs missing in war zone why? #393 
- [ ] Reward of warzone error #397 
- [ ] Xray step in #510 
- [ ] Questlog #1237 
- [ ] NPC Glomelvis The soul melody task doesn't work. #369
