### ISSUE TITLE
Item Issues

### ISSUE THREAD

**Issue by Royalot** [PrinterLUA/FORGOTTENSERVER-ORTS#542]
**I merge here all Item issues for better overview:**
- [x] ~~Claw of 'The Noxious Spawn' #539~~
- [x] ~~Party Cake dont work. #515~~
- [x] ~~Mushroom Beer Bug #508~~
- [x] ~~Sneaky Stabber of Eliteness #469~~
- [x] ~~Squeezing Gear of Girlpower #469~~
- [x] ~~Whacking Driller of Fate #469~~
- [x] ~~the umbral spellbook dont give the ml #591~~
