### ISSUE TITLE
[to-do] Addons

### ISSUE THREAD

**Issue by EPuncker** [PrinterLUA/FORGOTTENSERVER-ORTS#743]
Made this so we can track which addons quest we have working and revised (please only check the box after the quest was made into metatable, using storageTables, revised and tested ingame)

ref: http://tibia.wikia.com/wiki/Addon

- [x] Afflicted Outfits
- [x] Assassin Outfits
- [x] Barbarian Outfits
- [ ] Beggar Outfits
- [x] Brotherhood Outfits
- [ ] Cave Explorer Outfits
- [x] Citizen Outfits
- [x] Crystal Warlord Outfits
- [ ] Deepling Outfits
- [x] Demon Hunter Outfits
- [x] Demon Outfits
- [ ] Dream Warden Outfits
- [x] Druid Outfits
- [ ] Elementalist Outfits
- [ ] Glooth Engineer Outfits
- [x] Hunter Outfits
- [ ] Insectoid Outfits
- [ ] Jester Outfits
- [x] Knight Outfits
- [x] Mage Outfits
- [x] Nightmare Outfits
- [x] Nobleman Outfits
- [x] Norseman Outfits
- [ ] Oriental Outfits
- [x] Pirate Outfits
- [x] Shaman Outfits
- [x] Soil Guardian Outfits
- [x] Summoner Outfits
- [x] Warmaster Outfits
- [x] Warrior Outfits
- [ ] Wayfarer Outfits
- [x] Wizard Outfits
- [x] Yalaharian Outfits
