### ISSUE TITLE
Milestone 0.1

### ISSUE THREAD

**Issue by Skillert** [PrinterLUA/FORGOTTENSERVER-ORTS#781]
- [x] #405 | Fix door issue or replace doors with working ones?
- [x] #542 | Fix Claw of 'The Noxious Spawn'
- [x] #702 | Make @EPuncker purr purr purr!
- [x] #685 | Reach 100 of 240 tasks completed

NOTE:
This is just an "attempt" to see how well it would work with a Milestone.
@ninjalulz ,@Royalot: You can edit/close/remove if you think it's a bad idea. 

**EDIT**:
Small change regarding #542 since Mushroom Beer is more or less directly connected with the Bigfoot's burden quest, I think it will be better / easier to fix the Mushroom Beer bug together with the quest.

**EDIT for the EDIT**:
Seems like @TheSumm was in the craving for some Mushroom Beer since he fixed the bug, nice job!
