### ISSUE TITLE
Milestone 0.2

### ISSUE THREAD

**Issue by Skillert** [PrinterLUA/FORGOTTENSERVER-ORTS#796]
- [x] #781 | Complete last task for Milestone 0.1
- [ ] #795 | Make @EPuncker purr-a-long
- [x] #685 | Reach 120 of 240 tasks completed
- [x] #473 | Reach 20 of 28 tasks completed
