### ISSUE TITLE
[to-do] Ore wagon system

### ISSUE THREAD

**Issue by ghost** [PrinterLUA/FORGOTTENSERVER-ORTS#820]
we miss some things
- [x] map update do adapt the NPC in west of Kazordoon mountain
- [x] add "Your weekly ticket is still valid. Would be a waste of money to purchase a second one." if storage > 0

Add AID to ore wagons at:
- [x] west of Kazordoon mountain
- [x] south of Kazordoon, near the Dwarven Bridge
- [x] north of Kazordoon mountain
- [x] on top of the Kazordoon mountain, near a new Magic Carpet

and add its destination in script
