### ISSUE TITLE
Map issues (bugs and missing content)

### ISSUE THREAD

**Issue by Royalot** [PrinterLUA/FORGOTTENSERVER-ORTS#821]
**I merge here all Map issues to Keep better overview: Cause there are lot of Issues with mapbugs and have same name.**
**missing Content Need to be tracked**
- [x] Missing cave at northport #712 
- [x] ~~Missing map here: {x = 32473, y = 32174, z = 15} and here {x = 32475, y = 32155, z = 15} #774~~ 
- [x] ~~Missing map here: {x = 32782, y = 31634, z = 12} #774~~
- [ ] port hope #686 
- [ ] Cave missing Gray Island map. #677
- [ ] Island missing every spanw and lots of black tiles #592 
- [x] POI lever rooms revamp #576 
- [x] Crystal spider cave missing #324 
- [x] Errors in map.. revamp triangle tower #498 
- [ ] The Spike
- [x] The Spirit Grounds

**Map Bugs**
- [x] ~~Still trash on Roshamuul ground, example: {x = 33630, y = 32331, z = 7} #774~~
- [ ] mapbugs #776 
- [ ] Missing spawns for PH Bandit/Smuggler Cave, and Swamp Troll
