### ISSUE TITLE
[to-do] 10.x monsters

### ISSUE THREAD

**Issue by EPuncker** [PrinterLUA/FORGOTTENSERVER-ORTS#895]
- [ ] Blood Beast
- [ ] Devourer
- [x] Execowtioner
- [ ] Glooth Anemone
- [ ] Glooth Blob
- [ ] Glooth Golem
- [ ] Greater Death Minion
- [ ] Lesser Death Minion
- [ ] Metal Gargoyle
- [x] Minotaur Amazon
- [x] Minotaur Hunter
- [x] Mooh'Tah Warrior
- [x] Moohtant
- [ ] Rot Elemental
- [ ] Rustheap Golem
- [ ] Superior Death Minion
- [ ] Walker
- [x] Worm Priestess
- [x] Bullwark
- [ ] Death Priest Shargon
- [ ] Glooth Fairy
- [ ] Lisa
- [ ] The Ravager
