### ISSUE TITLE
[to-do] get rid off of compat.lua dependence

### ISSUE THREAD

**Issue by ghost** [PrinterLUA/FORGOTTENSERVER-ORTS#916]
lets start with something simple :)
- [ ] isPlayer(cid) => Player(cid)
- [ ] isMonster(cid) => Monster(cid)
- [ ] getCreatureName(cid) => Creature(cid):getName()
- [ ] getCreatureHealth(cid) => Creature(cid):getHealth()
- [ ] getCreatureMaxHealth(cid) => Creature(cid):getMaxHealth()
- [ ] getCreaturePosition(cid) => Creature(cid):getPosition()
- [ ] getCreatureOutfit(cid) => Creature(cid):getOutfit()
- [ ] getCreatureSpeed(cid) => Creature(cid):getSpeed()
- [ ] getCreatureBaseSpeed(cid) => Creature(cid):getBaseSpeed()
