### ISSUE TITLE
[to-do] Svargrond Arena

### ISSUE THREAD

**Issue by EPuncker** [PrinterLUA/FORGOTTENSERVER-ORTS#938]
- [ ] correct trophy message
- [ ] add so user can fight as many time as he want to
- [x] questlog?
- [ ] add last player name who did arena on statues
- [x] achievements
