### ISSUE TITLE
[to-do] Unranked Killing in the Name of... tasks

### ISSUE THREAD

**Issue by EPuncker** [PrinterLUA/FORGOTTENSERVER-ORTS#952]
Info from: http://tibia.wikia.com/wiki/Killing_in_the_Name_of..._Quest/Spoiler

- Daniel Steelsoul tasks:
- [ ] 100 Trolls and Troll Champions
- [ ] 150 Goblins, Goblin Assassins, Goblin Scavengers
- [ ] 300 Rotworms and Carrion Worms
- [ ] 500 Cyclopes, Cyclops Drones, Cyclops Smiths

- Gabel
- [ ] 500 Green Djinn and Efreet

- Malor
- [ ] 500 Blue Djinn and Marid

- Raymond Striker
- [ ] 3,000 Pirate Marauders, Pirate Cutthroats, Pirate Buccaneers, Pirate Corsairs
- [ ] 3,000 Pirate Marauders, Pirate Cutthroats, Pirate Buccaneers, Pirate Corsairs

- Budrik
- [ ] 5,000 Minotaurs

- Lugri
- [ ] 4,000 Necromancers
- [ ] 1,000 Necromancers
