### ISSUE TITLE
[to-do] Telas

### ISSUE THREAD

**Issue by EPuncker** [PrinterLUA/FORGOTTENSERVER-ORTS#980]
http://tibia.wikia.com/wiki/Telas

- [ ] If you say "crystal pedestal" to him he will buy all pedestals in any colour state in your inventory.
- [ ] add transcripts
- [x] update item sale list
- [ ] make it only tradeable after completing Shadows of Yalahar Quest.
